import {ChangeDetectionStrategy, Component} from '@angular/core';
import {FrameComponent} from './frame/frame.component';
import {FrameSales} from '../../Models/frameSales.models';

@Component({
  selector: 'app-display-production',
  imports: [
    FrameComponent
  ],
  templateUrl: './display-production.component.html',
  styleUrl: './display-production.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DisplayProductionComponent {

  cartList: FrameSales[] = [];
  addItem(item:FrameSales){
    this.cartList.push(item);
  }

  framedisplay:FrameSales[] = [
    {
      id: 1,
      text1: 'Giảm',
      percentage1: '21%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/m/image_1396_1.png",
      description: 'Apple MacBook Air M2 2024 8CPU 8GPU 16GB 256GB I Chính hãng Apple Việt Nam',
      saleprice: '19.650.000đ',
      originalprice: '24.990.000đ',
      smemberdiscount: 'Smember giảm đến 197.000đ',
      sstudentdiscount:'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 4.9,
    },
    {
      id: 2,
      text1: 'Giảm',
      percentage1: '8%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_11_1.png",
      description: 'MacBook Air M4 13 inch 2025 10CPU 8GPU 16GB 256GB | Chính hãng Apple Việt Nam',
      saleprice: '24.790.000đ',
      originalprice: '26.990.000đ',
      smemberdiscount: 'Smember giảm đến 248.000đ',
      sstudentdiscount:'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 5,
    },
    {
      id: 3,
      text1: 'Giảm',
      percentage1: '4%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_7_1.png",
      description: 'Mac mini M4 2024 10CPU 10GPU 16GB 256GB | Chính hãng Apple Việt Nam',
      saleprice: '14.390.000đ',
      originalprice: '14.990.000đ',
      smemberdiscount: 'Smember giảm đến 144.000đ',
      sstudentdiscount:'S-Student giảm đến 431.700đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 5,
    },
    {
      id: 4,
      text1: 'Giảm',
      percentage1: '5%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_4__7.png",
      description: 'MacBook Pro 14 M4 10CPU 10GPU 16GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '37.990.000đ',
      originalprice: '39.990.000đ',
      smemberdiscount: 'Smember giảm đến 380.000đ',
      sstudentdiscount:'S-Student giảm đến 500.700đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 5,
    },
    {
      id: 5,
      text1: 'Giảm',
      percentage1: '6%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_1__4_1.png",
      description: 'MacBook Air M4 13 inch 2025 10CPU 10GPU 16GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '29.990.000đ',
      originalprice: '31.990.000đ',
      smemberdiscount: 'Smember giảm đến 300.000đ',
      sstudentdiscount:'S-Student giảm đến 500.700đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 5,
    },
    {
      id: 6,
      text1: 'Giảm',
      percentage1: '9%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_11_1_2.png",
      description: 'MacBook Air M4 13 inch 2025 10CPU 8GPU 16GB 256GB Sạc 70W | Chính hãng Apple Việt Nam',
      saleprice: '25.590.000đ',
      originalprice: '27.990.000đ',
      smemberdiscount: 'Smember giảm đến 260.000đ',
      sstudentdiscount: '',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 7,
      text1: 'Giảm',
      percentage1: '4%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_9__4.png",
      description: 'MacBook Pro 14 M4 Pro 12CPU 16GPU 24GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '47.990.000đ',
      originalprice: '49.990.000đ',
      smemberdiscount: 'Smember giảm đến 480.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 4.8,
    },
    {
      id: 8,
      text1: 'Giảm',
      percentage1: '2%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_8.png",
      description: 'MacBook Pro 14 M4 10CPU 10GPU 24GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '44.190.000đ',
      originalprice: '44.990.000đ',
      smemberdiscount: 'Smember giảm đến 442.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 9,
      text1: 'Giảm',
      percentage1: '16%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/r/group_562.png",
      description: 'MacBook Pro 16 M3 Max 36GB - 1TB | Chính hãng Apple Việt Nam',
      saleprice: '75.990.000đ',
      originalprice: '89.990.000đ',
      smemberdiscount: 'Smember giảm đến 760.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 10,
      text1: 'Giảm',
      percentage1: '5%',
      text2: 'Trả góp',
      percentage2: '0%',
      img: "https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_2__21.png",
      description: 'MacBook Air M4 13 inch 2025 10CPU 10GPU 24GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '34.990.000đ',
      originalprice: '36.990.000đ',
      smemberdiscount: 'Smember giảm đến 350.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 11,
      text1: 'Giảm',
      percentage1: '4%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_1__2_3.png",
      description: 'Mac mini M4 2024 10CPU 10GPU 16GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '19.290.000đ',
      originalprice: '19.990.000đ',
      smemberdiscount: 'Smember giảm đến 193.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 12,
      text1: 'Giảm',
      percentage1: '8%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_1__4_1_2.png",
      description: 'MacBook Air M4 13 inch 2025 10CPU 10GPU 16GB 512GB Sạc 70W | Chính hãng Apple Việt Nam',
      saleprice: '30.490.000đ',
      originalprice: '32.990.000đ',
      smemberdiscount: 'Smember giảm đến 305.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 13,
      text1: 'Giảm',
      percentage1: '',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_11.png",
      description: 'Mac mini M4 2024 10CPU 10GPU 24GB 256GB | Chính hãng Apple Việt Nam',
      saleprice: '19.990.000đ',
      originalprice: '',
      smemberdiscount: 'Smember giảm đến 200.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 14,
      text1: 'Giảm',
      percentage1: '10%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/r/group_524_2_.png",
      description: 'Apple MacBook Air M2 2024 8CPU 10GPU 16GB 512GB Sạc 70W I Chính hãng Apple Việt Nam',
      saleprice: '26.990.000đ',
      originalprice: '29.990.000đ',
      smemberdiscount: 'Smember giảm đến 270.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 4.3,
    },
    {
      id: 15,
      text1: 'Giảm',
      percentage1: '1%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_2__13.png",
      description: 'Mac mini M4 2024 10CPU 10GPU 24GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '24.790.000đ',
      originalprice: '24.990.000đ',
      smemberdiscount: 'Smember giảm đến 248.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 16,
      text1: 'Giảm',
      percentage1: '6%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_4__1_3_2.png",
      description: 'MacBook Air M4 15 inch 2025 10CPU 10GPU 16GB 512GB Sạc 70W | Chính hãng Apple Việt Nam',
      saleprice: '35.690.000đ',
      originalprice: '37.990.000đ',
      smemberdiscount: 'Smember giảm đến 375.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 17,
      text1: 'Giảm',
      percentage1: '8%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_3__15.png",
      description: 'MacBook Air M4 15 inch 2025 10CPU 10GPU 16GB 256GB | Chính hãng Apple Việt Nam',
      saleprice: '29.590.000đ',
      originalprice: '31.990.000đ',
      smemberdiscount: 'Smember giảm đến 296.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 5,
    },
    {
      id: 18,
      text1: 'Giảm',
      percentage1: '',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_10__4.png",
      description: 'Apple Mac Studio M4 Max 2025 14CPU 32GPU 36GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '57.990.000đ',
      originalprice: '',
      smemberdiscount: '',
      sstudentdiscount: '',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 19,
      text1: 'Giảm',
      percentage1: '14%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_8__2.png",
      description: 'MacBook Air M3 13 inch 2024 8CPU 10GPU 16GB 512GB | Chính hãng Apple Việt Nam',
      saleprice: '28.490.000đ',
      originalprice: '32.990.000đ',
      smemberdiscount: 'Smember giảm đến 285.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
    {
      id: 20,
      text1: 'Giảm',
      percentage1: '5%',
      text2: 'Trả góp',
      percentage2: '0%',
      img:"https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/macbook_1__2_2.png",
      description: 'iMac M4 2024 24 inch 8CPU 8GPU 16GB 256GB | Chính hãng Apple Việt Nam',
      saleprice: '33.090.000đ',
      originalprice: '34.990.000đ',
      smemberdiscount: 'Smember giảm đến 331.000đ',
      sstudentdiscount: 'S-Student giảm đến 500.000đ',
      description2: 'Không phí chuyển đổi khi trả góp 0% qua thẻ tín dụng kỳ hạn 3-6 tháng',
      star: 'star',
      rating: 0,
    },
  ]

}
